---
- name: Install greeter server
  hosts: example.com
  tasks:
  - name: Install pillow (required by greeter)
    apt: name=python3-pillow

  roles:
    - role: django
      django_project: greeter
      django_project_repository: https://github.com/djangodeployment/greeter.git
      django_user: greeter
      django_project_python: python3
      django_project_site_packages: yes
      django_domain: example.com
      django_secret_key: topsecret
      django_port: 8000
      gunicorn_workers: 4
